server:
  port: 9092
spring:
  datasource:
    username: system
    password: manager
    url: jdbc:oracle:thin:@localhost:1521/xe
    driver-class-name: jdbc.oracle.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
